apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  MYSQL_DB: {{ .Values.mariadb.database | quote }}
  MYSQL_TABLE: {{ .Values.mariadb.tableName | quote }}
  MYSQL_HOST: {{ .Values.env.mysqlHost | default .Values.mariadb.name | quote }}
  MYSQL_USER: "root"
  USER: {{ .Values.appUser | quote }}
  API_BASE_URL: {{ .Values.env.apiBaseUrl | quote }}
  VUE_APP_TITLE_IMAGE: {{ .Values.frontend.iconImage | quote }}