apiVersion: v1
kind: Service
metadata:
  name: {{.Values.frontend.name}}
  labels:
    app: {{.Values.frontend.name}}
spec:
  type: {{.Values.frontendServiceType}}
  ports:
    - port: 80
      targetPort: {{.Values.frontend.port}}
      protocol: TCP
  selector:
    app: {{.Values.frontend.name}}
