apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
type: Opaque
stringData:
  MARIADB_ROOT_PASSWORD: "{{ .Values.secret.rootPassword }}"
  MYSQL_PASSWORD: "{{ .Values.secret.rootPassword }}"
