apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api.name }}-svc 
  labels:
    app: {{ .Values.api.name }}
spec:
  type: {{ .Values.apiServiceType }}
  ports:
    - port: {{ .Values.api.port }}
      targetPort: http
      name: http
  selector:
    app: {{ .Values.api.name }}